### ISSUE TITLE
Please provide API and SPI layers for others (request).

### ISSUE THREAD

**Issue by shumy** [aleph-zero-foundation/AlephBFT#1]
These projects have so much potential for other applications than just cryptocurrencies and smart contracts. And by targeting only these use cases it limits the potential of the work being done.

Personalty I have many project that I can't simply do it in current techs, because of these approaches. There is always some requirement that doesn't fit. No pub/sub user controlled message queues, WASM vm with custom host API, access to local/private storage, access to contract fired events from outside demons, discarding the token and gas requirements (not always needed), plug a specific application DB, etc. [Tendermint](https://tendermint.com) is the only thing I can work with, but native modules requires Go language.

Since you are just starting. I have a request:
Expose your consensus protocol in a well defined and documented API, and work from there. Please don't just start to integrate with substrate and other stuff. Look at this example [Async Raft](https://async-raft.github.io/async-raft). This approach helps other people to join in with ease and extend your network. I.e. [CosmWasm](https://cosmwasm.com) started as an outside project and is now looking very good.

The consensus protocol is the most difficult part to tackle. If we have this, there's a lot of knowledgeable developers out there that can help you expand your tools. I would be happy to join on free time. But not willing to work on the consensus protocol itself, this is something yours.

Please don't try to do all the work by your self. Help other people to help.

**Comment by mike1729** [comment]
This is very important point, thank you very much for raising it and providing the examples. We'll definitely look into them as the very point of separating the consensus implementation from integration with substrate was to make rush general so that it may be reused by other projects. Currently, rush implements only a state machine of the consensus, ie it has to be given a network layer that provides several functionalities that were abstracted out of rush (as peer identification, hash calculation, connection reliablity etc). Of course, the specific form we require is the very matter of 'friendly matter'. 

We have just finished a refactor of the api, so you may check the new version. We'll check the links you provided and will ponder how to make the api more friendly but if you have some suggestions we would be more than grateful if you share them :)
